Feature
Ademola101/Enumerables pull request #1
Opened 2021-10-25 13:54 UTC by Ademola101

This project contains various enumerable methods in the Enumerable module. The methods were all implemented by me with aid of ruby techniques that I have learnt so far

2021-10-26 12:26 UTC, soieducation requested changes
# STATUS: CHANGES REQUIRED 🚦 

## Hello @Ademola101  :handshake: :handshake: :handshake: 
 Great work on your first attempt
### However, there are still changes to be made

# [Required Changes] :warning: 
- Check inline comments below
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

2021-10-26 12:26 UTC, soieducation commented on enumerable.rb
> +    end
- [ ] The return statement here is missing the "a" variable in the my_each block

2021-10-26 12:26 UTC, soieducation commented on enumerable.rb
> +  end
- [ ] This method doesn't return anything when its called with an array, kindly fix it.

2021-10-26 12:26 UTC, soieducation commented on enumerable.rb
> +  end
- [ ] my_any? method should test for Regexp too. Check test cases [here](https://ruby-doc.org/core-2.6.1/Enumerable.html#method-i-any-3F)
- [ ] my_any? method should test for Classes too. Check test cases [here](https://ruby-doc.org/core-2.6.1/Enumerable.html#method-i-any-3F)

2021-10-26 12:26 UTC, soieducation commented on enumerable.rb
> +  end
- [ ] my_none? method should test for Regexp too. Check test cases [here](https://ruby-doc.org/core-2.6.1/Enumerable.html#method-i-none-3F)
- [ ] my_none? method should test for Classes too. Check test cases [here](https://ruby-doc.org/core-2.6.1/Enumerable.html#method-i-none-3F)

2021-10-26 12:26 UTC, soieducation commented on enumerable.rb
> +  end
- [ ] Refactor my_inject to pass all tests cases in the documentation given above.

2021-11-03 20:36 UTC, soieducation requested changes
# STATUS: CHANGES REQUIRED 🚦 

## Hello @Ademola101  :handshake: :handshake: :handshake: 
 Great work so far

### However, there are still changes to be made

# [Required Changes] :warning: 
- [ ] All methods are not passing except `my_each`, `my_each_with_index` and `my_select`. Kindly refactor and test again.
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

2021-11-05 08:12 UTC, soieducation requested changes
# STATUS: CHANGES REQUIRED 🚦 

## Hello @  :handshake: :handshake: :handshake: 
 Great work so far, you are almost there

### However, there are still changes to be made

# Required Changes :warning: 
- [ ] Check inline comments
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

2021-11-05 08:12 UTC, soieducation commented on enumerable.rb
> +  end
- [ ]  This method returns true for all test cases, kindly fix this
![Screenshot (305)](https://user-images.githubusercontent.com/86371332/140478950-21cb3452-991d-4214-8590-2284fbf188d7.png)

2021-11-05 11:20 UTC, soieducation approved these changes
## Status: Approved :green_circle: 

### Hello @Ademola101   :wave: 

### You have done an amazing job on this project, congratulations! Your project is approved :clap: :clap: :clap: 

Good luck with your next project :rocket: 

### Remember to submit your project completion form
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

2021-11-05 11:36 UTC, Ademola101 commented
Thank you for the review and the suggestions

2021-11-05 11:36 UTC, merged